In [2]:
import numpy as np
from numpy.linalg import eigh

## 1. Simulate any random rectangular matrix A.


In [3]:
A= np.asmatrix(np.random.rand(3, 4))
A

matrix([[0.82161784, 0.222226  , 0.44835297, 0.34545037],
        [0.36664833, 0.19559553, 0.81023541, 0.4778556 ],
        [0.29491704, 0.49689361, 0.22579375, 0.6459373 ]])

### 1.1
Rank of matrix A: The rank of a rectangular matrix is the maximum number of linearly independent rows or columns of the matrix. To find the rank of a rectangular matrix using Python, we can use the numpy.linalg.matrix_rank()

In [4]:
rank = np.linalg.matrix_rank(A)
print('Then rank of the matrix with shape {} is {}'.format(A.shape,rank))

Then rank of the matrix with shape (3, 4) is 3


### 1.2
The Determinant of a rectangular matrix does not exist, that is why when using np.linalg.det it gives an error

In [5]:
import traceback
try:
    np.linalg.det(A)
except:
    traceback.print_exc(limit=1)

Traceback (most recent call last):
  File "C:\Users\JUAN CHAVERRA\AppData\Local\Temp\ipykernel_6460\70908450.py", line 3, in <module>
    np.linalg.det(A)
numpy.linalg.LinAlgError: Last 2 dimensions of the array must be square


###  1.3
Invert a matrix using numpy.linalg.  Invert A: Using np.linalg Compute the (Moore-Penrose) pseudo-inverse of a matrix. 

In [6]:
A_inv = np.linalg.pinv(A)
A_inv

matrix([[ 1.71225155, -0.83442859, -0.35272474],
        [-0.16494718, -0.41858414,  1.12243889],
        [-0.43935813,  1.63541618, -0.76859483],
        [-0.50129733,  0.13130105,  1.11440496]])

###  1.4
How are eigenvalues and eigenvectors of A’A and AA’ related?  

Eigenvalues--> For this matrix I will use np.linalg.eig.  eig works for general matrices and therefore uses a slower algorithm

In [7]:
print(np.linalg.eig(np.dot(A.T, A))[0])
print(np.linalg.eig(np.dot(A, A.T))[0])

[2.48517609e+00 2.42449858e-01 1.76783784e-01 1.49532228e-16]
[2.48517609 0.17678378 0.24244986]


### What interesting differences can you notice between both?

The value are different because Rectangular matrices do not have eigenvectors/eigvalues. Instead they have singular values & singular vectors. (Square matrices have both - eigenvalues and singular values).